integrate with api for login feature
matkono/HealthSupApp pull request #1
Opened 2020-05-22 17:58 UTC by ShibaharaLH

## What this PR does

- Add integration between API and mobile application;
- Check expiration time of the JWT token;

## How to check if this PR is correct

- Verify if status code of each request and API is authorization and login credential;

## Evidences: 

- When authentication is authorized and login credential is correct:

![image](https://user-images.githubusercontent.com/44846533/82621380-5f620f00-9bb1-11ea-864a-8fd3b4d82ca0.png)

- When authentication is authorized and login credential is incorrect:

![image](https://user-images.githubusercontent.com/44846533/82621418-74d73900-9bb1-11ea-82dc-83358bfd548b.png)

- When authentication is unauthorized and login credential is correct:

![image](https://user-images.githubusercontent.com/44846533/82618988-ff686a00-9baa-11ea-86f4-84292bf8cf31.png)

- When authentication is authorized but email or password was not filled:

![image](https://user-images.githubusercontent.com/44846533/82622470-50c92700-9bb4-11ea-99fe-208da2766e70.png)

2020-05-23 19:59 UTC, KellyMBentes commented on lib/features/data/datasources/remote_datasource.dart
> +      final isValidHost = host == "10.0.2.2";
Será que não era melhor parametrizar essa linha?

2020-05-23 19:59 UTC, KellyMBentes commented on lib/features/data/datasources/remote_datasource.dart
> +    String urlLogin ='https://10.0.2.2:5001/api/v1/Doctor/login';
Será que não era melhor parametrizar essa parte? Pode usar o settings

2020-05-23 19:59 UTC, KellyMBentes commented on lib/features/data/repositories/doctor_repository_impl.dart
> +  Future<bool> getLoginDataFromDataSource(String email, String password) {
Transformar em Either<Failure, bool> e fazer um try catch pra capturar as excessões

2020-05-23 19:59 UTC, KellyMBentes commented on lib/features/data/datasources/remote_datasource.dart
> +    Map login = {
Usar o toMap no modelo

2020-05-23 19:59 UTC, KellyMBentes commented on lib/features/data/datasources/remote_datasource.dart
> +  Future<void> downloadToCache() async {
Essa função faz parte do local

2020-05-23 19:59 UTC, KellyMBentes commented on lib/features/domain/usecases/doctor_usecase.dart
> +  Future<bool> call(Params params) async {
Deveria ser um either

2020-05-23 20:00 UTC, matkono requested changes

2020-05-23 20:00 UTC, matkono commented on lib/features/data/datasources/remote_datasource2.dart
> +class CustomCacheManager extends BaseCacheManager {
Pode remover essa classe, acredito que tenha sido com o proposito de testes.

2020-05-23 20:00 UTC, matkono commented on lib/features/data/models/loginAPI_model.dart
> +class LoginAPIModel extends Login {
Acredito que `AuthenticateApiModel` seja melhor

2020-05-23 20:00 UTC, matkono commented on lib/features/domain/entities/login.dart
>  class Login extends Equatable {
Acredito que Authenticate seja melhor

2020-05-23 20:02 UTC, KellyMBentes commented on lib/features/data/datasources/remote_datasource.dart
> +  Future<bool> getLoginDataFromAPI(String email, String password) async {
Deveria ter um try catch pra tratar os possiveis erros

2020-05-23 20:02 UTC, KellyMBentes commented on pubspec.lock
>        name: archive
Esse arquivo deveria estar no git ignore

2020-06-13 17:31 UTC, ShibaharaLH commented on lib/features/data/datasources/remote_datasource.dart
> +      final isValidHost = host == "10.0.2.2";
Feito
![image](https://user-images.githubusercontent.com/44846533/84575309-8eb80600-ad82-11ea-9363-85baf8a7d1ca.png)

2020-06-13 17:32 UTC, ShibaharaLH commented on lib/features/data/datasources/remote_datasource.dart
> +    String urlLogin ='https://10.0.2.2:5001/api/v1/Doctor/login';
Feito
![image](https://user-images.githubusercontent.com/44846533/84575328-b5763c80-ad82-11ea-9fc7-3bd1ccb1649b.png)

2020-06-13 17:34 UTC, ShibaharaLH commented on lib/features/data/repositories/doctor_repository_impl.dart
> +  Future<bool> getLoginDataFromDataSource(String email, String password) {
Feito
![image](https://user-images.githubusercontent.com/44846533/84575383-07b75d80-ad83-11ea-9eb2-93aa7b71f762.png)

2020-06-13 17:57 UTC, ShibaharaLH commented on lib/features/data/datasources/remote_datasource.dart
> +    Map login = {
Feito
![image](https://user-images.githubusercontent.com/44846533/84575765-23703300-ad86-11ea-86ba-f2d0a46f103d.png)

2020-06-13 17:59 UTC, ShibaharaLH commented on lib/features/domain/usecases/doctor_usecase.dart
> +  Future<bool> call(Params params) async {
Feito
![image](https://user-images.githubusercontent.com/44846533/84575803-67633800-ad86-11ea-8929-dd81cf2ba624.png)

2020-06-13 18:00 UTC, ShibaharaLH commented on lib/features/data/models/loginAPI_model.dart
> +class LoginAPIModel extends Login {
Feito
![image](https://user-images.githubusercontent.com/44846533/84575834-97aad680-ad86-11ea-969d-327021bce905.png)

2020-06-13 18:00 UTC, ShibaharaLH commented on lib/features/domain/entities/login.dart
>  class Login extends Equatable {
Feito
![image](https://user-images.githubusercontent.com/44846533/84575840-a3969880-ad86-11ea-8f1b-f189e87fb416.png)

2020-06-13 18:01 UTC, ShibaharaLH commented on lib/features/data/datasources/remote_datasource.dart
> +  Future<bool> getLoginDataFromAPI(String email, String password) async {
Feito
![image](https://user-images.githubusercontent.com/44846533/84575846-b27d4b00-ad86-11ea-9c75-47e176856f63.png)

2020-06-13 18:02 UTC, ShibaharaLH commented on lib/features/data/datasources/remote_datasource2.dart
> +class CustomCacheManager extends BaseCacheManager {
Feito
Classe removida!

2020-06-13 18:02 UTC, ShibaharaLH commented on lib/features/data/datasources/remote_datasource.dart
> +  Future<void> downloadToCache() async {
Feito
Método removido!

2020-06-14 21:02 UTC, ShibaharaLH commented on lib/features/data/repositories/doctor_repository_impl.dart
> +  Future<bool> getLoginDataFromDataSource(String email, String password) {
Feito
![image](https://user-images.githubusercontent.com/44846533/84603966-2abc3d00-ae69-11ea-8294-39b0e476ae95.png)

2020-06-14 21:03 UTC, ShibaharaLH commented on lib/features/domain/usecases/doctor_usecase.dart
> +  Future<bool> call(Params params) async {
Feito
![image](https://user-images.githubusercontent.com/44846533/84603992-44f61b00-ae69-11ea-9613-53601f0c92be.png)

2020-06-14 21:03 UTC, ShibaharaLH commented on lib/features/data/datasources/remote_datasource.dart
> +  Future<bool> getLoginDataFromAPI(String email, String password) async {
Feito
![image](https://user-images.githubusercontent.com/44846533/84604000-5c350880-ae69-11ea-88e8-eb48c9259ec1.png)

2020-06-17 22:53 UTC, matkono approved these changes

2020-06-17 23:12 UTC, ShibaharaLH commented on pubspec.lock
>        name: archive
Será no próximo PR.

2020-06-17 23:13 UTC, merged